# https://github.com/sanbornhilland/label-issues-with-pull-request
labelPullRequests:
    # This label will be applied to issues addressed by an open PR.
    labelName: in progress
    # List of keywords that will trigger pull requests to be labeled.
    keywords:
      - Close
      - Closes
      - Closed
      - Fix
      - Fixes
      - Fixed
      - Resolve
      - Resolves
      - Resolved

# Configuration for welcome - https://github.com/behaviorbot/welcome
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
  When you have resolved the review comments, or if you need to discuss a comment.
  Could you please go into Reviewable and write 'Done' (or click the done-button)
  on each of the review comments. This allows me to acknowledge (resolve) the
  review comments and I know that you are done with each change. After you written
  'Done' on each review comment,  or comment on the review comment if it needs
  further discussion, then click the big green 'Publish' button on top of the page.
  That will send all your comments back as one big comment to this PR.
  You find Reviewable if you click on the big purple Reviewable-button in the PR description.

firstPRMergeComment: >
  Thanks for contributing!
